### ISSUE TITLE
End-Time-Tracking Page

### ISSUE THREAD

**Issue by sfxon** [sfxon/Dirty-Little-Helper#5]
File for demo-application is in local project on steves computer:
modal-demo.html

---

When I finish a timetracking, I want to open a new page, where I can enter data about the tracked time.

# Page  Properties

Our page should at least have this properties:

* Project-Selector
  * An element to select the project that this timetracking was taken for. 
  * It should make it possible to select a project.
  * Since we can have a lot of projects, it should load projects dynamically (by ajax calls).
    * It should use a search function for this purpose, which should show the search suggestions when you type the first letters. 

* Toggleable elements for working times:
  * Starttime 
  * Endtime
  * These elements are initially hidden, and should be able to be displayed.
  
* Checkbox "Billing"

* Comment-Textfield
  * Textfield to add a comment.
  
* Buttons: 
    * Save button
    * Close button. 
    
* Dialog should be a static backdrop modal, vertical and horizontal centered.

---

- [x] Bootstrap-Popup Beispiele ansehen
- [x] In einer kleinen Demo-Anwendung unser Popup erstellen (außerhalb des Projekts)
  - [x] Project selector (as a simple dropdown)
  - [x] Togglebar for timetrackings.
  - [x] Checkbox "Billing"
  - [x] Comment-Textfield
  - [x] Buttons
  - [x] Make sure, modal is static backdrop and vertical and horizontal centered.

- [x] Build "save" functionality
- [x] Build redirect functionality. If I come from the projects overview, i want to be redirected to the projects overviev. If i come from the trackedtimes overview, I want to be redirected to the trackedtimes overview.
- Make some design improvements on the project search-input-field: 
  - [x] Make position of search result list absolute.
  - [x] Remove rounded borders at bottom of text-input.
  - [x] Remove rounded borders at top of search-result-list.
  - [x] Show list in size of number of search results.
- [x] Show a text, when no results where found: "No results, e.g. "Keine Ergebnisse"
- [x] Make select list readonly, when no results where found, 
- [x] Remove readonly property from select (search result), when results have been found.
- [x] Close result list, when it is clicked, also when there where no search results.
- [x] Close result list, when I click somewhere on the page. (I think the best solution is, to use the focus-out event of the search input box)
- [x] Transform Javascript to Object-oriented format
- [x] Abstract parts of javascript, so it can be used in general.
